spring:
    datasource:
      url: jdbc:mysql://localhost:3306/lingxi-server?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: me.happycao.lingxi.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8090
  servlet-path: /lingxi/*

logging:
  level:
    com:
      abc: DEBUG

rss-path:
  windowsPath: D:/Temp/lingxi/upload/
  linuxPath: /usr/local/lingxi/upload/
